/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.BookingController;
import dao.BookingDao;
import dao.PaymentDao;
import model.User;
import model.Passenger;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;
import java.awt.*;

public class Booking extends JFrame {

    private User currentUser;
    private int flightId;
    private String route;
    private String time;
    private double price;
    private int travellers;

    public Booking(User user, int flightId, String route, String time, double price, int travellers) {
        this.currentUser = user;
        this.flightId = flightId;
        this.route = route;
        this.time = time;
        this.price = price;
        this.travellers = travellers;
        initComponents();
        setTitle("Booking - Uunchai ");
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        loadFlightInfo();
    }

    private void loadFlightInfo() {
        txtFlightInfo.setText(route + " | " + time + " | NPR " + price);
        txtFlightInfo.setEditable(false);
        spTravellers.setValue(travellers);
 
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFlightInfo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtName1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAge1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        spTravellers = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        btnBook = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        cmbGender1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(null);

        jToolBar1.setBackground(new java.awt.Color(51, 153, 255));
        jToolBar1.setRollover(true);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Complete Your Booking");
        jToolBar1.add(jLabel6);

        jPanel1.add(jToolBar1);
        jToolBar1.setBounds(0, 0, 800, 60);

        jPanel2.setBackground(new java.awt.Color(113, 171, 252));
        jPanel2.setLayout(null);

        jLabel1.setText("Flight Info");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(30, 20, 80, 20);
        jPanel2.add(txtFlightInfo);
        txtFlightInfo.setBounds(30, 50, 180, 30);

        jLabel2.setText("Passenger Name");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 120, 130, 16);
        jPanel2.add(txtName1);
        txtName1.setBounds(30, 150, 190, 30);

        jLabel3.setText("Age");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(330, 120, 37, 16);
        jPanel2.add(txtAge1);
        txtAge1.setBounds(330, 140, 180, 30);

        jLabel4.setText("Number of Travellers");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(330, 30, 130, 16);
        jPanel2.add(spTravellers);
        spTravellers.setBounds(330, 60, 190, 30);

        jLabel5.setText("Gender");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(30, 210, 70, 16);

        btnBook.setBackground(new java.awt.Color(51, 153, 255));
        btnBook.setText("Proceed to Payment");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });
        jPanel2.add(btnBook);
        btnBook.setBounds(120, 310, 140, 40);

        btnCancel.setBackground(new java.awt.Color(51, 153, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancel);
        btnCancel.setBounds(340, 310, 130, 40);

        cmbGender1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));
        jPanel2.add(cmbGender1);
        cmbGender1.setBounds(30, 230, 190, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(90, 100, 600, 430);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Flight Details");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(90, 70, 100, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
int choice = JOptionPane.showConfirmDialog(this, "Cancel booking?", "Confirm", JOptionPane.YES_NO_OPTION);
    if (choice == JOptionPane.YES_OPTION) {
        dispose();
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
 String name = txtName1.getText().trim();
        String ageStr = txtAge1.getText().trim();
        String gender = (String) cmbGender1.getSelectedItem();
        int travellers = (Integer) spTravellers.getValue();

        // Validation
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter passenger name", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int age;
        try {
            age = Integer.parseInt(ageStr);
            if (age <= 0 || age > 120) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Please enter a valid age (1-120)", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (travellers <= 0) {
            JOptionPane.showMessageDialog(this, "Number of travellers must be at least 1", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Calculate total amount
        double totalAmount = price * travellers;

        // Create passenger list (required by your confirmBooking method)
        List<Passenger> passengers = new ArrayList<>();
        passengers.add(new Passenger(name, age, gender));

        // Call your existing confirmBooking method
        BookingController bookingController = new BookingController();
        String pnr = bookingController.confirmBooking(
            currentUser.getId(),     // userId
            flightId,                // flightId
            travellers,              // numPassengers
            totalAmount,             // totalAmount
            passengers               // List<Passenger>
        );

        if (pnr == null) {
            JOptionPane.showMessageDialog(this, "Booking failed. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Success message
        JOptionPane.showMessageDialog(this,
            "Booking Confirmed!\nPNR: " + pnr + "\nProceeding to payment...",
            "Success", JOptionPane.INFORMATION_MESSAGE);

        // Navigate to Payment Page
        PaymentPage paymentPage = new PaymentPage(pnr, totalAmount, route, time, name, travellers);
        paymentPage.setVisible(true);

        // Close current booking window
        this.dispose();
    }//GEN-LAST:event_btnBookActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox<String> cmbGender1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JSpinner spTravellers;
    private javax.swing.JTextField txtAge1;
    private javax.swing.JTextField txtFlightInfo;
    private javax.swing.JTextField txtName1;
    // End of variables declaration//GEN-END:variables
}
