/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author A plus
 */
public class FlightBookingHistory extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FlightBookingHistory.class.getName());

    /**
     * Creates new form FlightHistory
     */
    public FlightBookingHistory() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        flightListPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        backbtn = new javax.swing.JButton();
        notibtn = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(null);

        flightListPanel.setBackground(new java.awt.Color(113, 171, 252));
        flightListPanel.setLayout(new javax.swing.BoxLayout(flightListPanel, javax.swing.BoxLayout.Y_AXIS));
        flightListPanel.add(jLabel3);

        jPanel1.add(flightListPanel);
        flightListPanel.setBounds(100, 90, 670, 450);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Flight Booking History");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(350, 60, 150, 20);

        backbtn.setBackground(new java.awt.Color(51, 102, 255));
        backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-back-arrow-20.png"))); // NOI18N
        backbtn.setBorder(null);
        backbtn.addActionListener(this::backbtnActionPerformed);
        jPanel1.add(backbtn);
        backbtn.setBounds(800, 10, 20, 20);

        notibtn.setBackground(new java.awt.Color(0, 102, 255));
        notibtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-notification-30.png"))); // NOI18N
        notibtn.setBorder(null);
        jPanel1.add(notibtn);
        notibtn.setBounds(750, 10, 30, 30);

        jToolBar2.setBackground(new java.awt.Color(51, 153, 255));
        jToolBar2.setRollover(true);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo 1.2.png"))); // NOI18N
        jToolBar2.add(jLabel25);

        jPanel1.add(jToolBar2);
        jToolBar2.setBounds(0, 0, 840, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 841, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FlightBookingHistory().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JPanel flightListPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JButton notibtn;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JPanel getFlightListPanel() {
    return flightListPanel; 
}
    
public javax.swing.JButton getBtnBack() {
    return backbtn; 
}
}
