/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.LoginController;
import model.User;
import javax.swing.*;

public class Login extends JFrame {
    private JTextField txtEmail;
    private JPasswordField txtPassword;
    private LoginController loginController;

    public Login() {
        loginController = new LoginController();
        initComponents();
       setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Email = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        showpassword = new javax.swing.JRadioButton();
        loginbtn = new javax.swing.JButton();
        forgotpassword = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        register = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(113, 171, 252));
        jPanel2.setLayout(null);

        Email.setText("Email:");
        jPanel2.add(Email);
        Email.setBounds(80, 180, 50, 16);

        Password.setText("Password:");
        jPanel2.add(Password);
        Password.setBounds(70, 240, 60, 16);

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel2.add(email);
        email.setBounds(140, 172, 230, 30);

        showpassword.setText("Show Password");
        showpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpasswordActionPerformed(evt);
            }
        });
        jPanel2.add(showpassword);
        showpassword.setBounds(140, 290, 110, 21);

        loginbtn.setBackground(new java.awt.Color(51, 153, 255));
        loginbtn.setText("Login");
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });
        jPanel2.add(loginbtn);
        loginbtn.setBounds(90, 340, 280, 30);

        forgotpassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        forgotpassword.setText("Forgot Password?");
        forgotpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotpasswordMouseClicked(evt);
            }
        });
        jPanel2.add(forgotpassword);
        forgotpassword.setBounds(190, 390, 110, 16);

        jLabel4.setText("Don't have an account?");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(130, 420, 130, 16);

        register.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        register.setText("Register");
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerMouseClicked(evt);
            }
        });
        jPanel2.add(register);
        register.setBounds(260, 420, 60, 16);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-user-48.png"))); // NOI18N
        jPanel2.add(jLabel6);
        jLabel6.setBounds(210, 10, 80, 70);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Login");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(220, 90, 50, 16);

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jPanel2.add(password);
        password.setBounds(140, 230, 230, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(210, 90, 440, 480);

        jToolBar1.setBackground(new java.awt.Color(51, 153, 255));
        jToolBar1.setRollover(true);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/company _logo.png"))); // NOI18N
        jToolBar1.add(jLabel8);

        jPanel1.add(jToolBar1);
        jToolBar1.setBounds(0, 0, 800, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
 password.requestFocusInWindow();        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
loginbtn.doClick();        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void showpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpasswordActionPerformed
  if (showpassword.isSelected()) {
        // Show password as plain text
        password.setEchoChar((char) 0);  // 0 means no hiding
    } else {
        // Hide password (default bullet ••••)
        password.setEchoChar('•');  
    } // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_showpasswordActionPerformed

    private void forgotpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotpasswordMouseClicked
this.dispose();
    new ResetPassword().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_forgotpasswordMouseClicked

    private void registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseClicked
this.dispose();
    new Registration().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_registerMouseClicked

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
String emailText = email.getText().trim();
    String passwordText = new String(password.getPassword());
    
    LoginController controller = new LoginController();
    controller.handleLogin(emailText, passwordText, this);        // TODO add your handling code here:
    }//GEN-LAST:event_loginbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception ex) {
        // Ignore look and feel errors — app will use default
        ex.printStackTrace();
    }

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> {
        new Login().setVisible(true);
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Password;
    private javax.swing.JTextField email;
    private javax.swing.JLabel forgotpassword;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton loginbtn;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel register;
    private javax.swing.JRadioButton showpassword;
    // End of variables declaration//GEN-END:variables
}
