/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author A plus
 */
public class PassengerForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PassengerForm.class.getName());

    /**
     * Creates new form PassengerForm
     */
    public PassengerForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel5 = new javax.swing.JLabel();
        logo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        fullname = new javax.swing.JTextField();
        continuebtn = new javax.swing.JButton();
        checkterm = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        cancelbtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        traveller = new javax.swing.JComboBox<>();
        Title1 = new javax.swing.JComboBox<>();

        title.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mr.", "Mrs.", "Ms" }));
        title.addActionListener(this::titleActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(null);

        jToolBar1.setBackground(new java.awt.Color(51, 153, 255));
        jToolBar1.setRollover(true);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo 1.2.png"))); // NOI18N
        jToolBar1.add(jLabel5);

        jPanel1.add(jToolBar1);
        jToolBar1.setBounds(0, 0, 910, 50);

        logo.setBackground(new java.awt.Color(113, 171, 252));
        logo.setLayout(null);

        jLabel1.setText("Title:");
        logo.add(jLabel1);
        jLabel1.setBounds(120, 100, 60, 16);

        jLabel2.setText("Full Name:");
        logo.add(jLabel2);
        jLabel2.setBounds(380, 100, 70, 16);

        jLabel3.setText("Contact:");
        logo.add(jLabel3);
        jLabel3.setBounds(380, 230, 80, 16);

        jLabel4.setText("Email:");
        logo.add(jLabel4);
        jLabel4.setBounds(120, 230, 70, 16);

        email.addActionListener(this::emailActionPerformed);
        logo.add(email);
        email.setBounds(120, 250, 190, 22);

        fullname.addActionListener(this::fullnameActionPerformed);
        logo.add(fullname);
        fullname.setBounds(380, 120, 220, 22);

        continuebtn.setBackground(new java.awt.Color(51, 153, 255));
        continuebtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        continuebtn.setText("Continue");
        continuebtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        continuebtn.addActionListener(this::continuebtnActionPerformed);
        logo.add(continuebtn);
        continuebtn.setBounds(140, 310, 90, 30);

        checkterm.setText("I agree with Terms & Conditions");
        checkterm.addActionListener(this::checktermActionPerformed);
        logo.add(checkterm);
        checkterm.setBounds(110, 370, 230, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Booking  Form");
        logo.add(jLabel6);
        jLabel6.setBounds(300, 20, 120, 20);

        cancelbtn.setBackground(new java.awt.Color(51, 153, 255));
        cancelbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancelbtn.setText("Cancel");
        cancelbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logo.add(cancelbtn);
        cancelbtn.setBounds(470, 310, 80, 30);

        jLabel7.setText("Traveller:");
        logo.add(jLabel7);
        jLabel7.setBounds(120, 170, 60, 16);

        jLabel8.setText("Age:");
        logo.add(jLabel8);
        jLabel8.setBounds(380, 170, 37, 16);

        age.addActionListener(this::ageActionPerformed);
        logo.add(age);
        age.setBounds(380, 190, 220, 22);

        contact.addActionListener(this::contactActionPerformed);
        logo.add(contact);
        contact.setBounds(380, 250, 220, 22);

        traveller.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adult", "Children(2-11 yrs)", "Senior Citizen(above 60 Yrs)" }));
        traveller.setSelectedIndex(-1);
        traveller.addActionListener(this::travellerActionPerformed);
        logo.add(traveller);
        traveller.setBounds(120, 190, 190, 22);

        Title1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mr.", "Mrs.", "Ms" }));
        Title1.setSelectedIndex(-1);
        Title1.addActionListener(this::Title1ActionPerformed);
        logo.add(Title1);
        Title1.setBounds(120, 120, 190, 22);

        jPanel1.add(logo);
        logo.setBounds(100, 70, 700, 420);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameActionPerformed

    private void checktermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checktermActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checktermActionPerformed

    private void continuebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_continuebtnActionPerformed

    private void titleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactActionPerformed

    private void travellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_travellerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_travellerActionPerformed

    private void Title1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Title1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Title1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PassengerForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Title1;
    private javax.swing.JTextField age;
    private javax.swing.JButton cancelbtn;
    private javax.swing.JCheckBox checkterm;
    private javax.swing.JTextField contact;
    private javax.swing.JButton continuebtn;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fullname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel logo;
    private javax.swing.JComboBox<String> title;
    private javax.swing.JComboBox<String> traveller;
    // End of variables declaration//GEN-END:variables

public void addContinueListener(ActionListener listener) {
    continuebtn.addActionListener(listener);
}

public void addCancelListener(ActionListener listener) {
    cancelbtn.addActionListener(listener);
}


public javax.swing.JTextField getTxtFullName() { return fullname; }
public javax.swing.JTextField getTxtAge() { return age; }
public javax.swing.JComboBox getComboTitle() { return Title1;}
public javax.swing.JComboBox getComboTraveller() { return traveller; }
public javax.swing.JTextField getTxtContact() { return contact; }
public javax.swing.JTextField getTxtEmail() { return email; }
public javax.swing.JCheckBox getChkTerms() { return checkterm; }
}