/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ResetPasswordController;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

public class ResetPassword extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ResetPassword.class.getName());
    private ResetPasswordController controller;

    public ResetPassword() {
        initComponents();
        controller = new ResetPasswordController();

        // Load security question when user presses Enter in email field
        emailField.addActionListener(e -> loadSecurityQuestion());
    }

    // Method to load security question from database when email is entered
    private void loadSecurityQuestion() {
        String email = emailField.getText().trim();
        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your email first.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String question = controller.getSecurityQuestion(email);
        if (question == null) {
            // Message already shown by controller
            lblQuestion.setSelectedIndex(0); // reset to default
            return;
        }

        // Set the combo box to show the fetched question
        lblQuestion.setSelectedItem(question);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        resetBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        newPassField = new javax.swing.JPasswordField();
        confirmPassField = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        securityAnswer = new javax.swing.JTextField();
        lblQuestion = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setLayout(null);

        jToolBar1.setBackground(new java.awt.Color(51, 153, 255));
        jToolBar1.setRollover(true);
        jToolBar1.add(jLabel6);

        jPanel3.add(jToolBar1);
        jToolBar1.setBounds(0, 0, 810, 50);

        jPanel1.setBackground(new java.awt.Color(113, 171, 252));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Reset Passsword");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 30, 190, 40);

        jLabel2.setText("Email:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(100, 80, 40, 20);

        jLabel3.setText("New Password:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 200, 100, 20);

        jLabel4.setText("Conform password:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 240, 110, 20);

        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        jPanel1.add(emailField);
        emailField.setBounds(150, 80, 170, 30);

        resetBtn.setBackground(new java.awt.Color(51, 153, 255));
        resetBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        resetBtn.setText("Reset Password");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        jPanel1.add(resetBtn);
        resetBtn.setBounds(90, 300, 200, 23);

        backBtn.setBackground(new java.awt.Color(51, 153, 255));
        backBtn.setText("Back to Login");
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
        });
        jPanel1.add(backBtn);
        backBtn.setBounds(130, 340, 110, 23);
        jPanel1.add(newPassField);
        newPassField.setBounds(150, 200, 170, 30);
        jPanel1.add(confirmPassField);
        confirmPassField.setBounds(150, 240, 170, 30);

        jLabel5.setText("Security Question:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 120, 100, 16);

        jLabel7.setText("Answer:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(90, 160, 50, 16);
        jPanel1.add(securityAnswer);
        securityAnswer.setBounds(150, 160, 170, 30);

        lblQuestion.setModel(new javax.swing.DefaultComboBoxModel<>(
            new String[] {
                "Select a security question",
                "What is your favorite place?",
                "What is your pet's name?",
                "What was your first school?",
                "What is your mother's maiden name?"
            }
        ));
        jPanel1.add(lblQuestion);
        lblQuestion.setBounds(150, 120, 170, 30);

        jPanel3.add(jPanel1);
        jPanel1.setBounds(210, 90, 360, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
  // Get values from fields
      String email = emailField.getText().trim();
        String SecurityAnswer = securityAnswer.getText().trim();

        String newPassword = new String(newPassField.getPassword());
        String confirmPassword = new String(confirmPassField.getPassword());

        Object selected = lblQuestion.getSelectedItem();
        if (selected == null || selected.toString().equals("Select a security question") || selected.toString().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter email to load security question.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String selectedQuestion = selected.toString();

        boolean success = controller.handlePasswordReset(
            email,
            selectedQuestion,
            SecurityAnswer,
            newPassword,
            confirmPassword
        );

        if (success) {
            JOptionPane.showMessageDialog(this, "Password reset successful! Please login.", "Success", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            new Login().setVisible(true);
        }
        // Failure messages already handled in controller
    }//GEN-LAST:event_resetBtnActionPerformed

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
      int choice = JOptionPane.showConfirmDialog(this, 
        "Go back to Login?\nAny entered data will be lost.", 
        "Back to Login", 
        JOptionPane.YES_NO_OPTION);
    
    if (choice == JOptionPane.YES_OPTION) {
        this.dispose();
        new Login().setVisible(true);
    }  // TODO add your handling code here:
    }//GEN-LAST:event_backBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ResetPassword().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JPasswordField confirmPassField;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JComboBox<String> lblQuestion;
    private javax.swing.JPasswordField newPassField;
    private javax.swing.JButton resetBtn;
    private javax.swing.JTextField securityAnswer;
    // End of variables declaration//GEN-END:variables

public void AddUserListner(ActionListener listner){
    resetBtn.addActionListener(listner);
}
public void LoginUserListner(ActionListener listner){
    backBtn .addActionListener(listner);
}

public javax.swing.JTextField getPasswordField(){
    return newPassField;
}
public javax.swing.JTextField getEmailField(){
        return emailField;
}
public javax.swing.JTextField getPassword2Field(){
        return confirmPassField;
}
}
