/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.text.SimpleDateFormat;
import java.sql.ResultSet;
import view.FlightResults;
import dao.FlightDao;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import model.User;

/**
 *
 * @author Acer
 */
public class UserDashboard extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserDashboard.class.getName());
    private User currentUser;  // <-- Added this field

    /**
     * Creates new form UserDashboard
     */
    public UserDashboard(User user) {
        this.currentUser = user;
        initComponents();

        ButtonGroup tripTypeGroup = new ButtonGroup();
        tripTypeGroup.add(mountainFlightBtn);
        tripTypeGroup.add(multiCityBtn);
        tripTypeGroup.add(roundTripBtn);
        tripTypeGroup.add(oneWayBtn);
        oneWayBtn.setSelected(true);  // default

        // ADD THESE ACTION LISTENERS
        oneWayBtn.addActionListener(e -> showOneWay());
        roundTripBtn.addActionListener(e -> showRoundTrip());
        mountainFlightBtn.addActionListener(e -> showMountainFlight());
        multiCityBtn.addActionListener(e -> showMultiCity());

        // Initial state
        showOneWay();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        profile = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Logout = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        SearchFlights = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        From = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        To = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        mountainFlightBtn = new javax.swing.JToggleButton();
        multiCityBtn = new javax.swing.JToggleButton();
        roundTripBtn = new javax.swing.JToggleButton();
        oneWayBtn = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(null);

        jToolBar1.setBackground(new java.awt.Color(51, 153, 255));
        jToolBar1.setRollover(true);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/company _logo.png"))); // NOI18N
        jToolBar1.add(jLabel6);

        jPanel1.add(jToolBar1);
        jToolBar1.setBounds(0, 0, 800, 60);

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 51), 2));
        jPanel2.setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-dashboard-24.png"))); // NOI18N
        jLabel7.setText("Dashboard");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 30, 100, 20);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-airplane-24.png"))); // NOI18N
        jLabel8.setText("Flight");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 70, 90, 20);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-payment-30.png"))); // NOI18N
        jLabel9.setText("Payment");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 110, 80, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-feedback-30.png"))); // NOI18N
        jLabel10.setText("Feedback");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 200, 100, 30);

        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-profile-30.png"))); // NOI18N
        profile.setText("Profile");
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
        });
        jPanel2.add(profile);
        profile.setBounds(10, 280, 100, 40);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-settings-30.png"))); // NOI18N
        jLabel13.setText("Settings");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(10, 460, 100, 30);

        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-logout-30.png"))); // NOI18N
        Logout.setText("Logout");
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        jPanel2.add(Logout);
        Logout.setBounds(10, 500, 90, 30);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-plane-30.png"))); // NOI18N
        jLabel16.setText("My Bookings");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel16);
        jLabel16.setBounds(10, 150, 120, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-notification-30.png"))); // NOI18N
        jLabel5.setText("Notifications");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 250, 110, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 60, 190, 540);

        SearchFlights.setText("Search Flights");
        SearchFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchFlightsActionPerformed(evt);
            }
        });
        jPanel1.add(SearchFlights);
        SearchFlights.setBounds(240, 140, 510, 40);

        jPanel3.setBackground(new java.awt.Color(113, 171, 252));
        jPanel3.setLayout(null);

        jLabel1.setText("From:");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(20, 26, 31, 20);
        jPanel3.add(From);
        From.setBounds(60, 20, 190, 30);

        jLabel2.setText("To:");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(360, 30, 30, 16);
        jPanel3.add(To);
        To.setBounds(390, 20, 160, 30);

        jLabel3.setText("Date:");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(10, 70, 37, 16);
        jPanel3.add(jDateChooser1);
        jDateChooser1.setBounds(60, 60, 190, 30);

        jLabel4.setText("Traveller:");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(330, 70, 60, 16);
        jPanel3.add(jSpinner1);
        jSpinner1.setBounds(400, 60, 150, 30);

        jLabel15.setText("Return Date:");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(10, 120, 70, 16);
        jPanel3.add(jDateChooser2);
        jDateChooser2.setBounds(90, 120, 200, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(210, 220, 570, 200);

        mountainFlightBtn.setText("Mountain Flight");
        jPanel1.add(mountainFlightBtn);
        mountainFlightBtn.setBounds(200, 70, 140, 40);

        multiCityBtn.setText("Multi City");
        jPanel1.add(multiCityBtn);
        multiCityBtn.setBounds(350, 70, 140, 40);

        roundTripBtn.setText("Round Trip");
        jPanel1.add(roundTripBtn);
        roundTripBtn.setBounds(500, 70, 140, 40);

        oneWayBtn.setText("One Way");
        jPanel1.add(oneWayBtn);
        oneWayBtn.setBounds(650, 70, 130, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchFlightsActionPerformed
   String from = From.getText().trim();
        String to = To.getText().trim();
        java.util.Date depDate = jDateChooser1.getDate();

        if (depDate == null) {
            JOptionPane.showMessageDialog(this, "Please select departure date");
            return;
        }

        String depDateStr = new SimpleDateFormat("yyyy-MM-dd").format(depDate);

        // Handle different trip types
        if (mountainFlightBtn.isSelected()) {
            // Special case: ignore From/To, search all mountain flights on that date
            from = "Kathmandu";  // or use a flag
            to = "%";  // wildcard or special query
        } else if (from.isEmpty() || to.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter From and To cities");
            return;
        }

        java.util.Date retDate = jDateChooser2.getDate();
        String retDateStr = null;
        if (roundTripBtn.isSelected()) {
            if (retDate == null) {
                JOptionPane.showMessageDialog(this, "Please select return date");
                return;
            }
            retDateStr = new SimpleDateFormat("yyyy-MM-dd").format(retDate);
        }

        int travellers = (Integer) jSpinner1.getValue();
        if (travellers <= 0) {
            JOptionPane.showMessageDialog(this, "Please select at least 1 traveller");
            return;
        }

        FlightDao dao = new FlightDao();
        try (ResultSet rs = dao.searchFlights(from, to, depDateStr)) {
            FlightResults results = new FlightResults(rs, currentUser, travellers, roundTripBtn.isSelected() ? retDateStr : null);
            results.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Search error: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_SearchFlightsActionPerformed
private void showOneWay() {
        jLabel15.setVisible(false);  // "Return Date:"
        jDateChooser2.setVisible(false);
        From.setEnabled(true);
        To.setEnabled(true);
    }

    private void showRoundTrip() {
        jLabel15.setVisible(true);
        jDateChooser2.setVisible(true);
        From.setEnabled(true);
        To.setEnabled(true);
    }

    private void showMountainFlight() {
        jLabel15.setVisible(false);
        jDateChooser2.setVisible(false);

        // Auto-fill for Mountain Flight (common: Kathmandu → Everest Sightseeing)
        From.setText("Kathmandu");
        From.setEnabled(false);
        To.setText("Mountain Flight");
        To.setEnabled(false);

        JOptionPane.showMessageDialog(this, 
            "Mountain Flight selected!\nRoute: Kathmandu → Everest Region (Sightseeing)\nDate and travellers only required.",
            "Mountain Flight", JOptionPane.INFORMATION_MESSAGE);
    }

    private void showMultiCity() {
        jLabel15.setVisible(false);
        jDateChooser2.setVisible(false);

        // Simple placeholder — you can make dynamic later
        JOptionPane.showMessageDialog(this, 
            "Multi City feature is under development.\nFor now, use One Way or Round Trip.",
            "Multi City", JOptionPane.INFORMATION_MESSAGE);

        // Optional: reselect One Way
        oneWayBtn.setSelected(true);
    }
    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked
Userprofile profilePage = new Userprofile(currentUser);
    profilePage.setVisible(true);     // TODO add your handling code here:
    }//GEN-LAST:event_profileMouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
    if (currentUser == null) {
        JOptionPane.showMessageDialog(this, "User not logged in");
        return;
    }
    BookingHistory history = new BookingHistory(currentUser);
    history.setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
Login log = new Login();
       log.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_LogoutMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField From;
    private javax.swing.JLabel Logout;
    private javax.swing.JButton SearchFlights;
    private javax.swing.JTextField To;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToggleButton mountainFlightBtn;
    private javax.swing.JToggleButton multiCityBtn;
    private javax.swing.JToggleButton oneWayBtn;
    private javax.swing.JLabel profile;
    private javax.swing.JToggleButton roundTripBtn;
    // End of variables declaration//GEN-END:variables

}
