/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author DELL
 */
public class Userprofile extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Userprofile.class.getName());

    /**
     * Creates new form Userprofile
     */
    public Userprofile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        addacc = new javax.swing.JLabel();
        resetpss = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        savebtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        savebtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(null);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(260, 300, 0, 3);

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/uunchai70.jpg"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/back1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 874, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel17)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 970, 70);

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));
        jPanel3.setLayout(null);

        addacc.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        addacc.setText("Add Account");
        jPanel3.add(addacc);
        addacc.setBounds(220, 430, 100, 22);

        resetpss.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        resetpss.setText("Reset password");
        jPanel3.add(resetpss);
        resetpss.setBounds(210, 460, 130, 22);

        jLabel2.setText(" Iron Man");
        jLabel2.setOpaque(true);
        jPanel3.add(jLabel2);
        jLabel2.setBounds(200, 140, 73, 22);

        jLabel6.setText(" Uunchaigroup123@gmail.com");
        jLabel6.setOpaque(true);
        jPanel3.add(jLabel6);
        jLabel6.setBounds(190, 260, 220, 22);

        jLabel4.setText(" 9812345678");
        jLabel4.setOpaque(true);
        jPanel3.add(jLabel4);
        jLabel4.setBounds(200, 210, 100, 22);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons8-user-profile-50.png"))); // NOI18N
        jPanel3.add(jLabel10);
        jLabel10.setBounds(180, 0, 155, 157);

        savebtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        savebtn.setText("Exit");
        savebtn.addActionListener(this::savebtnActionPerformed);
        jPanel3.add(savebtn);
        savebtn.setBounds(140, 340, 72, 37);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setText("User Profile");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(210, 10, 90, 22);

        jLabel1.setText("Username:");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(70, 140, 80, 22);

        jLabel3.setText("Contact:");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(80, 200, 70, 22);

        jLabel5.setText("E-mail:");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(90, 250, 47, 22);

        savebtn1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        savebtn1.setText("Save");
        jPanel3.add(savebtn1);
        savebtn1.setBounds(320, 340, 72, 37);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(220, 110, 520, 580);

        jLabel1.setText("Username:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(250, 290, 80, 22);

        jLabel2.setText("Iron Man");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(440, 290, 100, 22);

        jLabel3.setText("Contact:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(250, 330, 70, 22);

        jLabel4.setText("9812345678");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(440, 330, 100, 22);

        jLabel5.setText("E-mail:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(250, 380, 47, 22);

        jLabel6.setText("Uunchaigroup123@gmail.com");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(440, 380, 220, 22);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setText("User Profile");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(330, 100, 90, 22);

        jLabel8.setBackground(new java.awt.Color(51, 51, 255));
        jLabel8.setText("  Save");
        jLabel8.setOpaque(true);
        jPanel1.add(jLabel8);
        jLabel8.setBounds(480, 450, 60, 40);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(260, 300, 50, 10);

        jLabel9.setBackground(new java.awt.Color(51, 51, 255));
        jLabel9.setText("    Exit");
        jLabel9.setOpaque(true);
        jPanel1.add(jLabel9);
        jLabel9.setBounds(250, 452, 60, 40);

        lnlProfilePic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnlProfilePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons8-profile-30.png"))); // NOI18N
        lnlProfilePic.setPreferredSize(new java.awt.Dimension(120, 120));
        jPanel1.add(lnlProfilePic);
        lnlProfilePic.setBounds(300, 140, 160, 160);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 971, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Userprofile().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addacc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel resetpss;
    private javax.swing.JButton savebtn;
    private javax.swing.JButton savebtn1;
    // End of variables declaration//GEN-END:variables
}
private void setProfileImage() {
    ImageIcon icon = new ImageIcon(getClass().getResource("/images/profile.png"));
    Image img = icon.getImage();

    Image scaledImg = img.getScaledInstance(
            lblProfilePic.getWidth(),
            lblProfilePic.getHeight(),
            Image.SCALE_SMOOTH
    );

    lblProfilePic.setIcon(new ImageIcon(scaledImg));
}
