/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author DELL
 */
public class Userprofile extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Userprofile.class.getName());

    /**
     * Creates new form Userprofile
     */
    public Userprofile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        lnlProfilePic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(null);

        jLabel1.setText("Username:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(250, 290, 80, 16);

        jLabel2.setText("Iron Man");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(440, 290, 100, 16);

        jLabel3.setText("Contact:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(250, 330, 70, 16);

        jLabel4.setText("9812345678");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(440, 330, 100, 16);

        jLabel5.setText("E-mail:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(250, 380, 37, 16);

        jLabel6.setText("Uunchaigroup123@gmail.com");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(440, 380, 220, 16);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setText("User Profile");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(330, 100, 90, 22);

        jLabel8.setBackground(new java.awt.Color(51, 51, 255));
        jLabel8.setText("  Save");
        jLabel8.setOpaque(true);
        jPanel1.add(jLabel8);
        jLabel8.setBounds(470, 450, 60, 40);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(260, 300, 0, 3);

        jLabel9.setBackground(new java.awt.Color(51, 51, 255));
        jLabel9.setText("    Exit");
        jLabel9.setOpaque(true);
        jPanel1.add(jLabel9);
        jLabel9.setBounds(250, 452, 60, 40);

        lnlProfilePic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnlProfilePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons8-profile-30.png"))); // NOI18N
        lnlProfilePic.setPreferredSize(new java.awt.Dimension(120, 120));
        jPanel1.add(lnlProfilePic);
        lnlProfilePic.setBounds(300, 140, 160, 160);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Userprofile().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lnlProfilePic;
    // End of variables declaration//GEN-END:variables
}
private void setProfileImage() {
    ImageIcon icon = new ImageIcon(getClass().getResource("/images/profile.png"));
    Image img = icon.getImage();

    Image scaledImg = img.getScaledInstance(
            lblProfilePic.getWidth(),
            lblProfilePic.getHeight(),
            Image.SCALE_SMOOTH
    );

    lblProfilePic.setIcon(new ImageIcon(scaledImg));
}
